= 기능구현
Sejong Park <devsejong@gmail.com>
:toc:

== CRC카드

https://www.youtube.com/watch?v=iDZvUTXMYbg

CRC 카드는 개체 후보(Candidate)를 뽑아서, 그 후보가 다하여야 할 책임(Responsiblity)과 그 후보와 협력(Collaboration)해서 일을 하는 다른 개체 후보의 이름을 적어놓은 카드를 말한다. CRC란 Candidate, Responsiblity, Collaboration의 약자이다.

[.lead]
CRC카드로 책임과 역할을 부여해봅시다.

여전히 상상의 영역이긴하지만요...

상영(Showing)::
알고있음:::
* 영화관을 알고 있다.
* 영화를 알고 있다.
* 시간을 알고 있다.
* 가격을 알고 있다.
역할:::
* 상영별 좌석정보를 표현할 수 있다.
* 좌석을 예약 또는, 취소할 수 있다.
협력객체:::
* 영화관
* 영화
* 가격정책

***

영화(Movie)::
알고있음:::
* 영화 정보(이름, 내용)을 가지고 있다.
* 영화 유형을 알고있다.(3D, 일반)
역할:::
* 영화정보 만들기 및 수정(MovieService)
협력객체:::
??

***

영화관(Theater)::
알고있음:::
* 영화관정보
* 좌석정보
역할:::
* 좌석정보를 반환한다.
협력객체:::
* 좌석(좌석은 영화관과 생명주기가 동일)

***

가격정책(PriceRule)::
알고있음:::
역할:::
* 시간별 가격 정책
* 날짜별 가격 정책
협력객체:::
* 영화

== 상영은 누가 만드나요?

영화관, 영화, 상영은 누가 우위에 있는지를 정할 수 없다.
상영정보는 영화관, 영화 누구도 만들어줄 수 없다. 상영을 만들어주기 위해서는 가격정책또한 필요하지만 이 또한 상영을 만들어주는 주체로 볼 수 없다.

상영 정보를 만들어주는 다른 상위객체가 필요할 것이다.

`ShowingCreator`라는 객체를 새롭게 도입하도록 하자. 이 객체의 역할은 다음과 같다.

상영생성자(ShowingCreator)::
알고있음:::
역할:::
* 상영을 만들 수 있다.
협력객체:::
* 영화
* 가격정책
* 영화관

TIP: 모델 그림으로 그리기

== 코딩시작하기

가장 쉬운것부터!

협력객체 영화관, 영화 만들기
