= 기능구현
Sejong Park <devsejong@gmail.com>
:toc:

== CRC카드로 도메인 추출해보기

앞서서 용어정리와 대략적인 요구사항을 통해서 객체의 역할이 무엇인지를 뽑아내려 노력하였지만 그럼에도 시작점을 찾아내지 못하고 있었고, 코딩단계도 자연스레 지연되게 되었다. 이리저리 고민하던 중 CRC카드 기법을 통해서 객체를 좀더 시각화 해보도록 하였다.

* https://www.youtube.com/watch?v=iDZvUTXMYbg

CRC 카드는 개체 후보(Candidate)를 뽑아서, 그 후보가 다하여야 할 책임(Responsiblity)과 그 후보와 협력(Collaboration)해서 일을 하는 다른 개체 후보의 이름을 적어놓은 카드를 말한다. CRC란 Candidate, Responsiblity, Collaboration의 약자이다. 이를 통해서 우리는 각 도메인이 어떠한 역할을 하는지를 찾아낼 수 있다.

[.lead]
CRC카드로 객체들의 책임과 역할을 부여해보자!

상영(Showing)::
알고있음:::
* 영화관을 알고 있다.
* 영화를 알고 있다.
* 시간을 알고 있다.
* 가격을 알고 있다.
역할:::
* 상영별 좌석정보를 표현할 수 있다.
* 좌석을 예약 또는, 취소할 수 있다.
협력객체:::
* 영화관
* 영화
* 가격정책

***

영화(Movie)::
알고있음:::
* 영화 정보(이름, 내용)을 가지고 있다.
* 영화 유형을 알고있다.(3D, 일반)
역할:::
* 영화정보 만들기 및 수정(MovieService)
협력객체:::
??

***

영화관(Theater)::
알고있음:::
* 영화관정보
* 좌석정보
역할:::
* 좌석정보를 반환한다.
협력객체:::
* 좌석(좌석은 영화관과 생명주기가 동일)

***

가격정책(PriceRule)::
알고있음:::
역할:::
* 시간별 가격 정책
* 날짜별 가격 정책
협력객체:::
* 영화

=== 상영은 누가 만드나요?

영화관, 영화, 상영 두 객체를 비교해 보았을때 어느 객체가 높은 지위를 가지는지를 쉽사리 정할 수 없다. 서로간 연관관계를 가진것은 분명해 보인다. 상영을 위해서는 영화관과 영화 들 다 필요하며, 여기에 더해서 가격정보를 함께 가지고 있기 때문이다.

새롭게 서비스를 하나 정의하도록 하자 이 서비스는 영화관과 영화정보 그리고 상영정보를 기준으로 상영 도메인을 생성하는 역할을 부여한다. `ShowingCreatorService`라는 클래스를 새롭게 정의하도록 하자.

상영생성자(ShowingCreator)::
알고있음:::
역할:::
* 상영(Showing)을 만들수 있다.
협력객체:::
* 가격정책
* 영화
* 영화관


=== `용어정리`보단 `CRC카드`

첫번째 Overview에서 뽑아본 용어와 모델 관계도를 통해서 `예약`이라는 객체를 추출해내고 이를 중심으로 작업을 진행하려고 했었지만, CRC를 통해서 오히려 `상영`객체가 예약의 주체가 되는것이 더욱 옳다는것이 드러나게 되었다. 상영이라는 객체는 영화, 영화관, 시간을 담고 있으며, 예약에 필요한 모든 정보가 들어가있다. 가장 많이 관련된 정보를 알고 있는 객체에게 역할을 할당하는것이 옳은 설계라고 한다면, 상영 객체가 예매를 담당하는 주체로써 가장 좋은 객체일 것이다.

앞서 Overview에서 정의한 용어정리와 모델 그림은 폐기하기로 결정하였다. CRC카드만으로 충분히 객체의 역할과 용어정의까지 함께 할 수 있게 되었고 오히려 가독성도 향상되었기 때문이다. 위의 정리된 CRC카드는 `00.도메인정의.adoc`에서 지속적으로 업데이트 해나가기로 결정하였다.

== 상영 구현하기

`상영`을 만들어주는 역할을 지닌 `상영 생성자`의 테스트 코드를 작성하였다.

[source, java]
.ShowingCreatorServiceTest.class
----
@Test
public void create() {
    Showing showing = showingCreator.create("영화관", "영화", "시작시간", "금액");
}
----

테스트를 만들자 마자, 상영이 만들어지기 위해선 영화관이나 영화같은 협력객체들이 미리 준비되어야 한다는 것을 깨달았다. 아직까지 작은 코드에서 발전해나가는 방식은 어색하여 먼저 필요한 협력객체들을 만들어보기로 결정하였다.

=== 영화구현하기
