= 기능구현
Sejong Park <devsejong@gmail.com>
:toc:

== CRC카드로 도메인 추출해보기.

https://www.youtube.com/watch?v=iDZvUTXMYbg

CRC 카드는 개체 후보(Candidate)를 뽑아서, 그 후보가 다하여야 할 책임(Responsiblity)과 그 후보와 협력(Collaboration)해서 일을 하는 다른 개체 후보의 이름을 적어놓은 카드를 말한다. CRC란 Candidate, Responsiblity, Collaboration의 약자이다. 이를 통해서 우리는 각 도메인이 어떠한 역할을 하는지를 찾아낼 수 있다.

[.lead]
CRC카드로 책임과 역할을 부여해봅시다.

여전히 상상의 영역이긴하지만요...

상영(Showing)::
알고있음:::
* 영화관을 알고 있다.
* 영화를 알고 있다.
* 시간을 알고 있다.
* 가격을 알고 있다.
역할:::
* 상영별 좌석정보를 표현할 수 있다.
* 좌석을 예약 또는, 취소할 수 있다.
협력객체:::
* 영화관
* 영화
* 가격정책

***

영화(Movie)::
알고있음:::
* 영화 정보(이름, 내용)을 가지고 있다.
* 영화 유형을 알고있다.(3D, 일반)
역할:::
* 영화정보 만들기 및 수정(MovieService)
협력객체:::
??

***

영화관(Theater)::
알고있음:::
* 영화관정보
* 좌석정보
역할:::
* 좌석정보를 반환한다.
협력객체:::
* 좌석(좌석은 영화관과 생명주기가 동일)

***

가격정책(PriceRule)::
알고있음:::
역할:::
* 시간별 가격 정책
* 날짜별 가격 정책
협력객체:::
* 영화

== 상영은 누가 만드나요?

영화관, 영화, 상영 두 객체를 비교해 보았을때 어느 객체가 높은 지위를 가지는지를 쉽사리 정할 수 없다. 서로간 연관관계를 가진것은 분명해 보인다. 상영을 위해서는 영화관과 영화 들 다 필요하며, 여기에 더해서 가격정보를 함께 가지고 있기 때문이다.

새롭게 서비스를 하나 정의하도록 하자 이 서비스는 영화관과 영화정보 그리고 상영정보를 기준으로 상영 도메인을 생성하는 역할을 부여한다. `ShowingCreatorService`라는 클래스를 새롭게 정의하도록 하자.

상영생성자(ShowingCreator)::
알고있음:::
역할:::
* 상영(Showing)을 만들수 있다.
협력객체:::
* 가격정책
* 영화
* 영화관


== 코딩 시작

위에서 각 객체를 추출해낼 수 있었다. 이를 그림으로 그리면 다음과 같이 나타낼 수 있을 것이다.

//TODO 그림 그리기.

앞서 정의했던 모호한 요구사항을 위의 CRC카드 기법으로 좀 더 명확하게 뽑아낼 수 있게 되었다.

// 아래 이야기는 조금더 고민해보고 작성하기
// 영화관(Theater)객체를 생성해보도록 하자.
// 영화관이 있으면 당연히 좌석도 존재한다. 두 객체는 1:N의 관계이며, 함께 생성되고 동일한 생명주기를 가지게 될것이다. 하나의 단위로 생각해도 문제가 없을 것이다.
