= 상영 구현해보기
Sejong Park <devsejong@gmail.com>
:imagesDir: 03.상영
:toc:


WARNING: 생각나는대로 써내려가긴 했는데, 언제다듬지????? ㅠㅠㅠㅠㅠ


== CRC카드로 도메인 추출해보기

앞서서 용어정리와 대략적인 요구사항을 통해서 객체의 역할이 무엇인지를 뽑아내려 노력하였지만 그럼에도 시작점을 찾아내지 못하고 있었고, 코딩단계도 자연스레 지연되게 되었다. 이리저리 고민하던 중 CRC카드 기법을 통해서 객체를 좀더 시각화 해보도록 하였다.

* https://www.youtube.com/watch?v=iDZvUTXMYbg

CRC 카드는 개체 후보(Candidate)를 뽑아서, 그 후보가 다하여야 할 책임(Responsiblity)과 그 후보와 협력(Collaboration)해서 일을 하는 다른 개체 후보의 이름을 적어놓은 카드를 말한다. CRC란 Candidate, Responsiblity, Collaboration의 약자이다. 이를 통해서 우리는 각 도메인이 어떠한 역할을 하는지를 찾아낼 수 있다.

[.lead]
CRC카드로 객체들의 책임과 역할을 부여해보자!

상영(Showing)::
알고있음:::
* 영화관을 알고 있다.
* 영화를 알고 있다.
* 시간을 알고 있다.
* 가격을 알고 있다.
역할:::
* 상영별 좌석정보를 표현할 수 있다.
* 좌석을 예약 또는, 취소할 수 있다.
협력객체:::
* 영화관
* 영화
* 가격정책

***

영화(Movie)::
알고있음:::
* 영화 정보(이름, 내용)을 가지고 있다.
* 영화 유형을 알고있다.(3D, 일반)
역할:::
* 영화정보 만들기 및 수정(MovieService)
협력객체:::
??

***

영화관(Theater)::
알고있음:::
* 영화관정보
* 좌석정보
역할:::
* 좌석정보를 반환한다.
협력객체:::
* 좌석(좌석은 영화관과 생명주기가 동일)

***

가격정책(PriceRule)::
알고있음:::
역할:::
* 시간별 가격 정책
* 날짜별 가격 정책
협력객체:::
* 영화

=== 상영은 누가 만드나요?

영화관, 영화, 상영 두 객체를 비교해 보았을때 어느 객체가 높은 지위를 가지는지를 쉽사리 정할 수 없다. 서로간 연관관계를 가진것은 분명해 보인다. 상영을 위해서는 영화관과 영화 들 다 필요하며, 여기에 더해서 가격정보를 함께 가지고 있기 때문이다.

새롭게 서비스를 하나 정의하도록 하자 이 서비스는 영화관과 영화정보 그리고 상영정보를 기준으로 상영 도메인을 생성하는 역할을 부여한다. `ShowingCreatorService`라는 클래스를 새롭게 정의하도록 하자.

상영생성기(ShowingCreator)::
알고있음:::
역할:::
* 상영(Showing)을 만들수 있다.
협력객체:::
* 가격정책
* 영화
* 영화관


=== `용어정리`보단 `CRC카드`

첫번째 Overview에서 뽑아본 용어와 모델 관계도를 통해서 `예약`이라는 객체를 추출해내고 이를 중심으로 작업을 진행하려고 했었지만, CRC를 통해서 오히려 `상영`객체가 예약의 주체가 되는것이 더욱 옳다는것이 드러나게 되었다. 상영이라는 객체는 영화, 영화관, 시간을 담고 있으며, 예약에 필요한 모든 정보가 들어가있다. 가장 많이 관련된 정보를 알고 있는 객체에게 역할을 할당하는것이 옳은 설계라고 한다면, 상영 객체가 예매를 담당하는 주체로써 가장 좋은 객체일 것이다.

앞서 Overview에서 정의한 용어정리와 모델 그림은 폐기하기로 결정하였다. CRC카드만으로 충분히 객체의 역할과 용어정의까지 함께 할 수 있게 되었고 오히려 가독성도 향상되었기 때문이다. 위의 정리된 CRC카드는 `00.도메인정의.adoc`에서 지속적으로 업데이트 해나가기로 결정하였다.

== 상영 구현하기

`상영`을 만들어주는 역할을 지닌 `상영 생성기`의 테스트 코드를 작성하였다.

[source, java]
.ShowingCreatorServiceTest.class
----
@Test
public void create() {
    Showing showing = showingCreator.create("영화관", "영화", "시작시간", "금액");
}
----

테스트를 만들자 마자, 상영이 만들어지기 위해선 영화관이나 영화같은 협력객체들이 미리 준비되어야 한다는 것을 깨달았다. 아직까지 작은 코드에서 발전해나가는 방식은 어색하여 먼저 필요한 협력객체들을 만들어보기로 결정하였다.

=== 영화 구현하기

아래와 같이 `영화`엔티티를 만들었다. 영화는 영화는 IMAX, 3D등의 타입을 가질수 있다. 타입은 영화가 있어야지만 존재하는 값이므로 함께 값이 생성되도록 설정하였다.

[source, java]
----
@Entity
public class Movie {
    @Id
    @GeneratedValue
    private Long id;
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;
    private int runningTime;

    // 영화Type은 영화와 생명주기가 동일.
    @ElementCollection
    @CollectionTable(
            name = "MOVIE_AVAILABLE_TYPE",
            joinColumns = @JoinColumn(name = "MOVIE_ID")
    )
    private Set<MovieType> availableMovieType;

    //getter, constructor
}
----

엔티티의 저장역할을 맡는 `MovieService`도 생성하였다. 영화는 다른 협력객체가 없는 독립적인 존재이기 때문에 비교적 간략하게 만들어낼 수 있었다.

[source, java]
.MovieService.java
----
@Service
public class MovieService {
    @Autowired MovieRepository repository;

    public Movie create(MovieCreateRequest request) {
        Movie movie = new Movie(
                request.getName(),
                request.getDescription(),
                request.getRunningTime(),
                request.getMovieTypes()
        );

        return repository.save(movie);
    }

    public Movie get(long id) {
        return repository.getOne(id);
    }
}
----

=== 영화관 구현하기

영화관 역시 영화와 마찬가지로 협력객체가 존재하지 않는다. 다만 위의 영화와는 다르게 영화관에는 좌석이 함께 입력되어야 한다. 1:N관계는 객체지향적인 프로그래밍에선 쉽게 구현할 수 있지만 ORM과 연결되는 순간 쉽지 않은 작업이 되어 버린다. 영화관이 생성됨과 동시에 좌석도 함께 입력된다. 그렇기 때문에 동일한 생명주기를 가지게 되며, 별도의 테이블을 할당하여 Value Object로 만든 Seat가 입력되도록 만들어 주었다.

[source, java]
----
@Entity
public class Theater {
    @Id
    @GeneratedValue
    private Long id;
    private String name;

    @ElementCollection
    @CollectionTable(name = "THEATER_SEAT", joinColumns = @JoinColumn(name = "id"))
    @OrderColumn(name = "SEAT_IDX")
    private List<Seat> seats = new ArrayList<>();

    //getter, constructor
}
----

일반적으로 영화관에서 좌석은 다음과 같이 배정되곤 한다.

image::03.상영(Showing)-49aad.png[]

지금은 토이프로젝트이므로(핵심이 여기가 아님!!) 많이 고민하지 않고 가로 세로의 크기를 받아 직사각형의 좌석을 만들어주도록 설정하였다. y축은 알파벳을 사용하므로 숫자를 간략하게 알파벳으로 변경하는 로직은 좌석을 생성하는 주체인 Theater에 추가하였다.

[source, java]
.Seat.java
----
@Embeddable
public class Seat {
    private Character row;
    private Integer column;

    protected Seat() {
    }

    public Seat(Character row, Integer column) {
        this.row = row;
        this.column = column;
    }
}
----

[source, java]
.Theater.java
----
//.....

public Theater(String name, int columnSize, int rowSize) {
    //검증로직 생략
    this.name = name;
    this.seats = seatsGenerator(columnSize, rowSize);
}

// 좌석을 생성하여 리스트를 반환합니다.
private static List<Seat> seatsGenerator(int columnSize, int rowSize) {
    List<Seat> seats = new ArrayList<>();

    for (int row = 1; row <= rowSize; row++) {
        char rowString = getCharFromNumber(row);
        for (int column = 1; column <= columnSize; column++) {
            seats.add(new Seat(rowString, column));
        }
    }

    return seats;
}

// 좌석정보를 반환합니다.
private static char getCharFromNumber(int i) {
    if (i > 0 && i < 27)
        return (char) (i + 'A' - 1);
    else
        throw new IllegalArgumentException("문자변경 실패");
}

//.....
----

영화관 서비스는 다음과 같이 Theater의 생성자를 호출하도록 만들었다. 외부에서 값을 받을때 DTO의 형식으로 값을 가져오도록 만들었다.

[source, java]
.TheaterService.java
----
@Service
public class TheaterService {
    @Autowired TheaterRepsitory repository;

    // 영화관 정보를 생성합니다.
    public Theater create(TheaterCreateRequest request) {
        Theater theater = new Theater(request.getName(), request.getColumnSize(), request.getRowSize());
        repository.save(theater);

        return theater;
    }
}
----

=== `상영` 구현하기

비로소 상영을 구성할 수 있게 되었다. 상영에 필요한 협력객체들을 필드에 넣고 아래와 같이 엔티티를 만들어주었다.

[source, java]
.Showing.java
----
@Entity
public class Showing {

    @Id
    @GeneratedValue
    private Long id;
    @ManyToOne
    private Movie movie;
    @ManyToOne
    private Theater theater;
    private LocalDateTime startTime;
    private Money price;

    @OneToMany(mappedBy = "showing")
    private List<ShowingSeat> showingSeats = new ArrayList<>();

    protected Showing() {
    }
}
----

앞서 **상영을 통해서 좌석을 예매한다**라고 정의했다. 영화관의 `좌석`에서 범위가 다소 넓어져 `상영좌석`은 `상영`과 예매여부등이 추가로 필요하게 되었다. 즉 이전의 Seat에서 좀 더 확장된 개념을 가지며, 하나의 좌석에 따라 정보가 변경되므로 ValueObject가 아닌 `Entity`로 `ShowingSeat`를 구현하였다.

[source, java]
.ShowingSeat.java
----
@Entity
public class ShowingSeat {
    public enum State {RESERVED, VACANCY}

    @Id
    @GeneratedValue
    private Long id;
    @ManyToOne
    private Showing showing;
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "row", column = @Column(name = "SEAT_ROW")),
            @AttributeOverride(name = "column", column = @Column(name = "SEAT_COLUMN"))
    })
    private Seat seat;

    @Enumerated(EnumType.STRING)
    private State state;

    public ShowingSeat(Showing showing, Seat seat) {
        setShowing(showing);
        this.seat = seat;
        this.state = State.VACANCY;
    }
}
----

=== `상영 생성기`구현

WARN:: `상영좌석`에 대한 설명 추가

이제 상영을 생성하는 코드를 작성하여야 한다. 우리는 상영을 하나의 단위로 보기로 결정하였다. 즉 상영이라는 단위가 하나의 애그리거트가 되어야 한다. 하지만 이를 생성하는 작업은 쉽지 않다. 가장 큰 문제는 우리는 ORM을 사용하여 패러다임이 맞지 않은 두 기술들을 이어야 하기 때문이다. JPA로 좀더 이야기를 하자면 `상영좌석`은 `상영`엔티티에서 연관관계의 주인이 된다. 따라서 `상영`이 먼저 생성되고 `엔티티`로 등록되어야지만 `상영좌석`도 엔티티로 등록할 수 있게 된다.


테스트 코드는 위의 상태에서 실제 연관객체가 들어갔다는 점 외에는 달라진 부분이 없다. 아래와 같이 간략한 검증로직을 추가하여 테스트를 만들어 주었다.

[source, java]
----
@Test
public void create() throws Exception {
    // when
    Showing showing = showingCreator.create(theater, movie, startTime, Money.of(3000));

    // then
    assertThat(showing.getPrice(), is(Money.of(3000)));
    assertThat(showing.getMovie().getName(), is("WALL-E"));
    assertThat(showing.getTheater().getName(), is("서현점"));
}
----

상영이 생성될 때에는 많은 협력객체가 필요하기 때문에 앞서 `상영 생성기`를 별도의 객체로 분리시키기로 했었다. 앞서 이야기했던대로 `상영`의 생성자로 `상영좌석`까지 한꺼번에 생성할 수 없다. 그렇기 때문에 도메인로직은 최대한 캡슐화시킨다는 기본원칙이 다소 위배되는 코드가 나올수 밖에 없다. 다행히 복잡한 생성로직을 지금처럼 별도의 생성 클래스로 분리시켜 놓았고 앞으로 이 클래스의 밖으로 복잡함이 드러나지 않도록 조심하도록 하자.

[source, java]
.ShowingCreator.java
----
@Service
public class ShowingCreator {
    @Autowired ShowingRepository showingRepository;
    @Autowired ShowingSeatRepository seatRepository;

    public Showing create(Theater theater, Movie movie, LocalDateTime startTime, Money price) {
        // 상영좌석을 만들기 위해선 상영이 생성되어야 한다.
        Showing showing = new Showing(theater, movie, startTime, price);
        showingRepository.save(showing);

        // 상영 좌석 생성 하면서 상영 엔티티를 참조로 추가한다.
        List<ShowingSeat> showingSeats = theater.getSeats().stream()
                .map(seat -> new ShowingSeat(showing, seat))
                .collect(Collectors.toList());

        // 상영 좌석을 최종적으로 저장한다.
        seatRepository.save(showingSeats);
        return showing;
    }
}
----
